name: Build vBot

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.name }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            target: Win64

          - name: Android
            os: ubuntu-latest
            target: Android64

    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build vBot
        uses: geode-sdk/build-geode-mod@main
        with:
          combine: true
          target: ${{ matrix.config.target }}

  package:
    name: Package vBot
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Combine builds
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload combined .geode
        uses: actions/upload-artifact@v4
        with:
          name: vBot
          path: ${{ steps.build.outputs.build-output }}
